# Generated by Django 3.0.3 on 2020-04-08 00:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.IntegerField(choices=[(0, 'Rather Not Say'), (1, 'Male'), (2, 'Female'),
                                                        (3, 'Non-Conforming'), (4, 'Other')],
                                               default=0, verbose_name='gender')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar', verbose_name='picture')),
                ('interest1', models.TextField()),
                ('interest2', models.TextField()),
                ('interest3', models.TextField()),
                ('interest4', models.TextField()),
                ('interest5', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AutamaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autamaid', models.CharField(default='0', max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='Images')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('nummatches', models.CharField(default='0000000', editable=False, max_length=100)),
                ('owner', models.CharField(default='FREE', max_length=100)),
                ('pickle', models.CharField(default='PICKLE', max_length=100)),
                ('interest1', models.CharField(max_length=100)),
                ('interest2', models.CharField(max_length=100)),
                ('interest3', models.CharField(max_length=100)),
                ('interest4', models.CharField(max_length=100)),
                ('interest5', models.CharField(max_length=100)),
                ('interest6', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(choices=[('User', 'User'), ('Autama', 'Autama')], max_length=6)),
                ('autamaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AutamaProfile')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
