# Generated by Django 3.0.3 on 2020-03-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
                ('picture', models.FilePathField()),
                ('interests1', models.TextField()),
                ('interests2', models.TextField()),
                ('interests3', models.TextField()),
                ('interests4', models.TextField()),
                ('interests5', models.TextField()),
            ],
        ),
    ]
