# Generated by Django 3.0.3 on 2020-03-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutamaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autamaid', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='Images')),
            ],
        ),
    ]
