# Generated by Django 3.0.3 on 2020-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutamaProfile',
            fields=[
                ('autamaid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='Images')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('nummatches', models.CharField(default='0000000', editable=False, max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('pickle', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=100)),
            ],
        ),
    ]
