# Generated by Django 3.0.3 on 2020-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutamaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autamaid', models.CharField(default='0', max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='Images')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('nummatches', models.CharField(default='0000000', editable=False, max_length=100)),
                ('owner', models.CharField(default='FREE', max_length=100)),
                ('pickle', models.CharField(default='PICKLE', max_length=100)),
                ('interests', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
    ]
