# Generated by Django 3.0.3 on 2020-03-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutamaProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autamaprofile',
            name='first',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autamaprofile',
            name='last',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
